/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShiftRouteRouteImport } from './routes/_shift/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ShiftIndexRouteImport } from './routes/_shift/index'
import { Route as ShiftCreateRouteImport } from './routes/_shift/create'
import { Route as ShiftBulkCreateRouteImport } from './routes/_shift/bulk-create'
import { Route as ShiftShiftIdRouteImport } from './routes/_shift/$shiftId'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ShiftEditShiftIdRouteImport } from './routes/_shift/edit.$shiftId'

const ShiftRouteRoute = ShiftRouteRouteImport.update({
  id: '/_shift',
  getParentRoute: () => rootRouteImport,
})
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
})
const ShiftIndexRoute = ShiftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShiftRouteRoute,
})
const ShiftCreateRoute = ShiftCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ShiftRouteRoute,
})
const ShiftBulkCreateRoute = ShiftBulkCreateRouteImport.update({
  id: '/bulk-create',
  path: '/bulk-create',
  getParentRoute: () => ShiftRouteRoute,
})
const ShiftShiftIdRoute = ShiftShiftIdRouteImport.update({
  id: '/$shiftId',
  path: '/$shiftId',
  getParentRoute: () => ShiftRouteRoute,
})
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
})
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
})
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
})
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
})
const ShiftEditShiftIdRoute = ShiftEditShiftIdRouteImport.update({
  id: '/edit/$shiftId',
  path: '/edit/$shiftId',
  getParentRoute: () => ShiftRouteRoute,
})

const AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const ShiftRouteRouteChildren = {
  ShiftShiftIdRoute: ShiftShiftIdRoute,
  ShiftBulkCreateRoute: ShiftBulkCreateRoute,
  ShiftCreateRoute: ShiftCreateRoute,
  ShiftIndexRoute: ShiftIndexRoute,
  ShiftEditShiftIdRoute: ShiftEditShiftIdRoute,
}

const ShiftRouteRouteWithChildren = ShiftRouteRoute._addFileChildren(
  ShiftRouteRouteChildren,
)

const rootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ShiftRouteRoute: ShiftRouteRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
